# Build, package, and test the Frameworks SDK from {Aurora,Sunspot}
spec:
  inputs:
    runner:
      options: [aurora, aurora-eval, sunspot]
      default: aurora
      description: CI runners to use
    root_dir:
      rules:
        - if: $[[ inputs.runner ]] =~ '/^aurora.*/'
          default: '/lus/flare/projects/datascience/frameworks-ci'
        - if: $[[ inputs.runner ]] == 'sunspot'
          default: '/lus/tegu/projects/datascience/frameworks-ci'
      description: Directory to store built artifacts
    python_version:
      default: 3.12
      description: Python version to build against
    torch_version:
      default: main
      description: PyTorch version to build
    triton_version:
      default: main
      description: Triton-XPU version to build
    torchccl_version:
      default: ''
      description: torchCCL version to build
    ipex_version:
      default: ''
      description: IPEX version to build
    vllm_version:
      default: main
      description: vLLM version to build
    vllm_xpu_kernels_version:
      default: main
      description: vLLM XPU kernels version to build
---

variables:
  FRAMEWORKS_ROOT_DIR: $[[ inputs.root_dir ]]
  FRAMEWORKS_PYTHON_VERSION: $[[ inputs.python_version ]]
  FRAMEWORKS_TORCH_VERSION: $[[ inputs.torch_version ]]
  FRAMEWORKS_TRITON_VERSION: $[[ inputs.triton_version ]]
  FRAMEWORKS_TORCHCCL_VERSION: $[[ inputs.torchccl_version ]]
  FRAMEWORKS_IPEX_VERSION: $[[ inputs.ipex_version ]]
  FRAMEWORKS_VLLM_VERSION: $[[ inputs.vllm_version ]]
  FRAMEWORKS_VLLM_XPU_KERNELS_VERSION: $[[ inputs.vllm_xpu_kernels_version ]]

include:
  - local: 'templates/common.yml'
    inputs:
      runner: $[[ inputs.runner ]]

  # Nightly Wheels
  - local: 'templates/nightly-wheel.yml'
    inputs:
      wheel: triton
      needs: [llvm]
  - local: 'templates/nightly-wheel.yml'
    inputs:
      wheel: torch
      needs: [triton, pti-gpu]
  - local: 'templates/nightly-wheel.yml'
    inputs:
      wheel: intel_extension_for_pytorch
      needs: [torch]
    rules:
      - if: '"$[[ inputs.ipex_version ]]" != ""'
  - local: 'templates/nightly-wheel.yml'
    inputs:
      wheel: oneccl_bind_pt
      needs: [torch]
    rules:
      - if: '"$[[ inputs.torchccl_version ]]" != ""'
  - local: 'templates/nightly-wheel.yml'
    inputs:
      wheel: mpi4py
  - local: 'templates/nightly-wheel.yml'
    inputs:
      wheel: vllm
      needs: [torch]
  - local: 'templates/nightly-wheel.yml'
    inputs:
      wheel: vllm_xpu_kernels
      needs: [torch]
  - local: 'templates/nightly-wheel.yml'
    inputs:
      wheel: torchvision
      needs: [torch]

# Custom LLVM build for `triton-xpu`
llvm:
  stage: build
  extends: .common-runner
  script:
    - ./deps/llvm
  artifacts:
    when: always
    expire_in: never
    paths:
      - "*.log"

# Updated `pti-gpu` build
pti-gpu:
  stage: build
  extends: .common-runner
  script:
    - ./deps/pti-gpu
  artifacts:
    when: always
    expire_in: never
    paths:
      - "*.log"

test:
  stage: test
  extends: .common-runner
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - ./tests/bats/bin/bats tests/*.bats
